"""add table hisa

Revision ID: 10ff95a69e91
Revises: 9433a259641c
Create Date: 2021-05-27 14:29:15.227741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ff95a69e91'
down_revision = '9433a259641c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('high_interest_savings_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal', sa.Float(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('time_period', sa.Float(), nullable=True),
    sa.Column('payout_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('high_interest_savings_account')
    # ### end Alembic commands ###
